// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgoBiekjXrjNyOl_386qpVvke47RLGj10',
    appId: '1:533992069330:web:eae921ea36c006fa0db50b',
    messagingSenderId: '533992069330',
    projectId: 'app-entregas-flutter',
    authDomain: 'app-entregas-flutter.firebaseapp.com',
    storageBucket: 'app-entregas-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAPdO4LZDGvKe7zQdX7SodKWOYBw7my4s',
    appId: '1:533992069330:android:fd51bfac629761f40db50b',
    messagingSenderId: '533992069330',
    projectId: 'app-entregas-flutter',
    storageBucket: 'app-entregas-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg61Fdtrqh5_T6fpoMYQV3Ha4qsVTdQP8',
    appId: '1:533992069330:ios:18cb9fd0ddf0ec3e0db50b',
    messagingSenderId: '533992069330',
    projectId: 'app-entregas-flutter',
    storageBucket: 'app-entregas-flutter.firebasestorage.app',
    iosBundleId: 'com.example.appEntregas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg61Fdtrqh5_T6fpoMYQV3Ha4qsVTdQP8',
    appId: '1:533992069330:ios:18cb9fd0ddf0ec3e0db50b',
    messagingSenderId: '533992069330',
    projectId: 'app-entregas-flutter',
    storageBucket: 'app-entregas-flutter.firebasestorage.app',
    iosBundleId: 'com.example.appEntregas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgoBiekjXrjNyOl_386qpVvke47RLGj10',
    appId: '1:533992069330:web:4b2c4b6c704ebbb30db50b',
    messagingSenderId: '533992069330',
    projectId: 'app-entregas-flutter',
    authDomain: 'app-entregas-flutter.firebaseapp.com',
    storageBucket: 'app-entregas-flutter.firebasestorage.app',
  );
}
